/* eslint-disable */
// Generated by scripts/generate_widget_contracts.mjs. Do not edit by hand.

/**
 * Common wire envelope for all muno pre-templated widgets.
 */
export interface WidgetEnvelope {
  widget_type:
    | 'bot_text'
    | 'user_text'
    | 'typing_indicator'
    | 'date_range_picker'
    | 'party_picker'
    | 'place_autocomplete_input'
    | 'flight_list'
    | 'flight_card'
    | 'hotel_list'
    | 'hotel_card'
    | 'hotel_compare'
    | 'place_list'
    | 'place_card'
    | 'action_chooser'
    | 'map_view'
    | 'filter_panel'
    | 'property_block'
    | 'itinerary_summary'
    | 'order_confirmation'
    | 'notification'
    | 'error_card'
    | 'clarify_question'
    | 'loading_card'
    | 'calendar_view';
  variant: string;
  payload: {
    [k: string]: unknown;
  };
  ai_adjustments?: {
    emphasis?: string;
    annotations?: {
      target: string;
      text: string;
      kind?: 'info' | 'warning' | 'success' | 'error';
    }[];
    conditional_fields?: {
      [k: string]: string | number | boolean | null;
    };
  };
  schema_version: 1;
}


/**
 * Illustrated CTA row.
 */
export interface ActionChooserPayload {
  prompt_text: string;
  options: {
    label: string;
    action_id: string;
    illustration_url?: string;
  }[];
  submitted_value?: {
    action_id: string;
  };
}


/**
 * Bot bubble text. Markdown is allowed.
 */
export interface BotTextPayload {
  text: string;
  timestamp?: string;
  markdown?: boolean;
}


/**
 * Firestore-backed trip calendar view.
 */
export interface CalendarViewPayload {
  trip_id: string;
  events_path: string;
  display_events?: CalendarEvent[];
  editable: boolean;
  empty_state_text?: string;
}
export interface CalendarEvent {
  event_id: string;
  type: 'flight_depart' | 'flight_arrive' | 'check_in' | 'check_out' | 'activity' | 'user_note';
  start_at: string;
  end_at?: string | null;
  timezone: string;
  title: string;
  location: string;
  notes?: string | null;
  source_order_id?: string | null;
  source_hotel_id?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  google_calendar_event_id?: string | null;
}


/**
 * Clarifying question from the agent.
 */
export interface ClarifyQuestionPayload {
  question_text: string;
  options: {
    label: string;
    action_id: string;
  }[];
}


/**
 * Interactive date range picker.
 */
export interface DateRangePickerPayload {
  min_date: string;
  max_date: string;
  default_from?: string;
  default_to?: string;
  locale: 'en' | 'ru';
  submit: 'submit';
  submitted_value?: {
    from: string;
    to: string;
    nights: number;
  };
}


/**
 * Graceful failure card.
 */
export interface ErrorCardPayload {
  title: string;
  description: string;
  retry_action_id?: string;
  contact_support?: boolean;
}


/**
 * Right-pane interactive filters.
 */
export interface FilterPanelPayload {
  hotel_category_options: string[];
  budget_range: {
    min: number;
    max: number;
    currency: string;
  };
  guest_rating_options: number[];
  applied: {
    hotel_category?: string[];
    budget_min?: number;
    budget_max?: number;
    guest_rating_min?: number;
  };
  ctas?: ('clear_all' | 'apply')[];
}


/**
 * Single Duffel or Amadeus flight offer card.
 */
export interface FlightCardPayload {
  offer_id: string;
  price: {
    total: string;
    currency: string;
  };
  itineraries: {
    duration?: string;
    segments: {
      departure: {
        iata: string;
        at: string;
      };
      arrival: {
        iata: string;
        at: string;
      };
      carrier: string;
      flight_number?: string;
      duration: string;
      stops?: number;
    }[];
  }[];
  carriers: string[];
  duration: string;
  stops: number;
  validating_airline?: string;
  ctas?: ('view_details' | 'book_this')[];
  ai_adjustments?: {
    emphasis?: string;
    annotations?: {
      target: string;
      text: string;
      kind?: 'info' | 'warning' | 'success' | 'error';
    }[];
  };
}


/**
 * List of flight_card payloads.
 */
export interface FlightListPayload {
  title: string;
  items: FlightCardPayload[];
  emphasis_offer_id?: string;
  total_count: number;
  currency: string;
}
/**
 * Single Duffel or Amadeus flight offer card.
 */
export interface FlightCardPayload {
  offer_id: string;
  price: {
    total: string;
    currency: string;
  };
  itineraries: {
    duration?: string;
    segments: {
      departure: {
        iata: string;
        at: string;
      };
      arrival: {
        iata: string;
        at: string;
      };
      carrier: string;
      flight_number?: string;
      duration: string;
      stops?: number;
    }[];
  }[];
  carriers: string[];
  duration: string;
  stops: number;
  validating_airline?: string;
  ctas?: ('view_details' | 'book_this')[];
  ai_adjustments?: {
    emphasis?: string;
    annotations?: {
      target: string;
      text: string;
      kind?: 'info' | 'warning' | 'success' | 'error';
    }[];
  };
}


/**
 * Single hotel property card.
 */
export interface HotelCardPayload {
  hotel_id: string;
  name: string;
  location?: {
    lat?: number;
    lng?: number;
    city?: string;
  };
  star_rating?: number;
  score: number;
  score_count?: number;
  thumb_up_count?: number;
  thumb_down_count?: number;
  photos: string[];
  amenities: string[];
  price_per_night?: number;
  currency: string;
  rooms_matching?: number;
  available_rooms?: number;
  address?: string;
  distance_from_center?: string;
  ctas?: ('watch_in_detail' | 'show_numbers')[];
  ai_adjustments?: {
    emphasis?: string;
    annotations?: {
      target: string;
      text: string;
      kind?: 'info' | 'warning' | 'success' | 'error';
    }[];
    upsell_banner?: {
      text: string;
      action_label: string;
      action_id?: string;
    };
  };
}


/**
 * Two hotel cards side-by-side.
 */
export interface HotelComparePayload {
  /**
   * @minItems 2
   * @maxItems 2
   */
  items: [HotelCardPayload, HotelCardPayload];
  comparison_facets: string[];
}
/**
 * Single hotel property card.
 */
export interface HotelCardPayload {
  hotel_id: string;
  name: string;
  location?: {
    lat?: number;
    lng?: number;
    city?: string;
  };
  star_rating?: number;
  score: number;
  score_count?: number;
  thumb_up_count?: number;
  thumb_down_count?: number;
  photos: string[];
  amenities: string[];
  price_per_night?: number;
  currency: string;
  rooms_matching?: number;
  available_rooms?: number;
  address?: string;
  distance_from_center?: string;
  ctas?: ('watch_in_detail' | 'show_numbers')[];
  ai_adjustments?: {
    emphasis?: string;
    annotations?: {
      target: string;
      text: string;
      kind?: 'info' | 'warning' | 'success' | 'error';
    }[];
    upsell_banner?: {
      text: string;
      action_label: string;
      action_id?: string;
    };
  };
}


/**
 * List of hotel_card payloads.
 */
export interface HotelListPayload {
  title: string;
  items: HotelCardPayload[];
  total_count: number;
  filter_summary?: string;
  upsell_banner?: {
    text: string;
    action_label: string;
    action_id: string;
  };
}
/**
 * Single hotel property card.
 */
export interface HotelCardPayload {
  hotel_id: string;
  name: string;
  location?: {
    lat?: number;
    lng?: number;
    city?: string;
  };
  star_rating?: number;
  score: number;
  score_count?: number;
  thumb_up_count?: number;
  thumb_down_count?: number;
  photos: string[];
  amenities: string[];
  price_per_night?: number;
  currency: string;
  rooms_matching?: number;
  available_rooms?: number;
  address?: string;
  distance_from_center?: string;
  ctas?: ('watch_in_detail' | 'show_numbers')[];
  ai_adjustments?: {
    emphasis?: string;
    annotations?: {
      target: string;
      text: string;
      kind?: 'info' | 'warning' | 'success' | 'error';
    }[];
    upsell_banner?: {
      text: string;
      action_label: string;
      action_id?: string;
    };
  };
}


/**
 * End-of-flow itinerary review.
 */
export interface ItinerarySummaryPayload {
  destination: string;
  dates: {
    from: string;
    to: string;
  };
  traveller_party: {
    [k: string]: unknown;
  };
  picked_flight?: FlightCardPayload;
  picked_hotel?: HotelCardPayload;
  total_cost?: {
    amount?: number;
    currency?: string;
  };
  notes?: string;
  ctas?: ('confirm' | 'edit')[];
}
/**
 * Single Duffel or Amadeus flight offer card.
 */
export interface FlightCardPayload {
  offer_id: string;
  price: {
    total: string;
    currency: string;
  };
  itineraries: {
    duration?: string;
    segments: {
      departure: {
        iata: string;
        at: string;
      };
      arrival: {
        iata: string;
        at: string;
      };
      carrier: string;
      flight_number?: string;
      duration: string;
      stops?: number;
    }[];
  }[];
  carriers: string[];
  duration: string;
  stops: number;
  validating_airline?: string;
  ctas?: ('view_details' | 'book_this')[];
  ai_adjustments?: {
    emphasis?: string;
    annotations?: {
      target: string;
      text: string;
      kind?: 'info' | 'warning' | 'success' | 'error';
    }[];
  };
}
/**
 * Single hotel property card.
 */
export interface HotelCardPayload {
  hotel_id: string;
  name: string;
  location?: {
    lat?: number;
    lng?: number;
    city?: string;
  };
  star_rating?: number;
  score: number;
  score_count?: number;
  thumb_up_count?: number;
  thumb_down_count?: number;
  photos: string[];
  amenities: string[];
  price_per_night?: number;
  currency: string;
  rooms_matching?: number;
  available_rooms?: number;
  address?: string;
  distance_from_center?: string;
  ctas?: ('watch_in_detail' | 'show_numbers')[];
  ai_adjustments?: {
    emphasis?: string;
    annotations?: {
      target: string;
      text: string;
      kind?: 'info' | 'warning' | 'success' | 'error';
    }[];
    upsell_banner?: {
      text: string;
      action_label: string;
      action_id?: string;
    };
  };
}


/**
 * Async tool loading placeholder.
 */
export interface LoadingCardPayload {
  tool_name: string;
  started_at: string;
  expected_duration_seconds?: number;
}


/**
 * Full-bleed map state.
 */
export interface MapViewPayload {
  center: {
    lat: number;
    lng: number;
  };
  zoom: number;
  markers: {
    lat: number;
    lng: number;
    label: string;
    hotel_id?: string;
    state: 'normal' | 'selected' | 'viewed';
  }[];
  selected_marker_id?: string;
  filter_state?: {
    star_rating?: number[];
    budget_min?: number;
    budget_max?: number;
    guest_rating_min?: number;
  };
}


/**
 * Toast-style notification.
 */
export interface NotificationPayload {
  kind: 'info' | 'warning' | 'error' | 'success';
  text: string;
  dismissible?: boolean;
}


/**
 * Duffel test order receipt.
 */
export interface OrderConfirmationPayload {
  order_id: string;
  booking_reference: string;
  total_amount: string;
  total_currency: string;
  passengers?: {
    [k: string]: unknown;
  }[];
  slices?: {
    [k: string]: unknown;
  }[];
  ctas?: ('view_full' | 'new_search')[];
}


/**
 * Interactive traveller party picker.
 */
export interface PartyPickerPayload {
  rooms_max: number;
  adults_max: number;
  children_max: number;
  allow_child_ages: boolean;
  submitted_value?: {
    rooms: number;
    adults: number;
    children: {
      age: number;
    }[];
  };
}


/**
 * Destination autocomplete input.
 */
export interface PlaceAutocompleteInputPayload {
  placeholder: string;
  suggestions: {
    label: string;
    id: string;
    kind: 'airport' | 'city' | 'landmark';
  }[];
  submit_on_select: boolean;
  submitted_value?: {
    label: string;
    id: string;
    kind: 'airport' | 'city' | 'landmark';
  };
}


/**
 * Single place result.
 */
export interface PlaceCardPayload {
  place_id: string;
  name: string;
  types: string[];
  photos: string[];
  rating?: number;
  rating_count?: number;
  opening_hours?: string;
  address?: string;
  ctas?: ('view_details' | 'add_to_itinerary')[];
}


/**
 * List of place_card payloads.
 */
export interface PlaceListPayload {
  title: string;
  items: PlaceCardPayload[];
}
/**
 * Single place result.
 */
export interface PlaceCardPayload {
  place_id: string;
  name: string;
  types: string[];
  photos: string[];
  rating?: number;
  rating_count?: number;
  opening_hours?: string;
  address?: string;
  ctas?: ('view_details' | 'add_to_itinerary')[];
}


/**
 * Right-pane slot accumulator.
 */
export interface PropertyBlockPayload {
  slots: {
    label: string;
    value?: string | number | boolean | null;
    edit_action_id?: string;
    missing: boolean;
  }[];
}


/**
 * Typing indicator for an agent.
 */
export interface TypingIndicatorPayload {
  agent_name: string;
}


/**
 * User echo bubble.
 */
export interface UserTextPayload {
  text: string;
  timestamp?: string;
  user_avatar_url?: string;
}


export const WIDGET_TYPES = [
  "action_chooser",
  "bot_text",
  "calendar_view",
  "clarify_question",
  "date_range_picker",
  "error_card",
  "filter_panel",
  "flight_card",
  "flight_list",
  "hotel_card",
  "hotel_compare",
  "hotel_list",
  "itinerary_summary",
  "loading_card",
  "map_view",
  "notification",
  "order_confirmation",
  "party_picker",
  "place_autocomplete_input",
  "place_card",
  "place_list",
  "property_block",
  "typing_indicator",
  "user_text"
] as const;
export type WidgetType = typeof WIDGET_TYPES[number];
export type WidgetPayload = ActionChooserPayload | BotTextPayload | CalendarViewPayload | ClarifyQuestionPayload | DateRangePickerPayload | ErrorCardPayload | FilterPanelPayload | FlightCardPayload | FlightListPayload | HotelCardPayload | HotelComparePayload | HotelListPayload | ItinerarySummaryPayload | LoadingCardPayload | MapViewPayload | NotificationPayload | OrderConfirmationPayload | PartyPickerPayload | PlaceAutocompleteInputPayload | PlaceCardPayload | PlaceListPayload | PropertyBlockPayload | TypingIndicatorPayload | UserTextPayload;
export type WidgetEnvelopeOf<TPayload = WidgetPayload> = WidgetEnvelope & { payload: TPayload };
