import { compileFromFile } from 'json-schema-to-typescript';
import { readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const schemaDir = path.join(root, 'playbooks', 'widget-contract');
const outFile = path.join(root, 'src', 'contracts', 'widgets.ts');
const files = (await readdir(schemaDir)).filter((file) => file.endsWith('.schema.json')).sort();
const declarations = [];
for (const file of files) {
  declarations.push(await compileFromFile(path.join(schemaDir, file), {
    bannerComment: '',
    cwd: schemaDir,
    style: { singleQuote: true, semi: true }
  }));
}
const widgetTypes = files.filter((file) => file !== '_envelope.schema.json').map((file) => file.replace('.schema.json', ''));
const pascal = (value) => value.split('_').map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join('');
const payloadTypes = widgetTypes.map((name) => `${pascal(name)}Payload`).join(' | ');
const body = [
  '/* eslint-disable */',
  '// Generated by scripts/generate_widget_contracts.mjs. Do not edit by hand.',
  '',
  declarations.join('\n\n'),
  '',
  `export const WIDGET_TYPES = ${JSON.stringify(widgetTypes, null, 2)} as const;`,
  'export type WidgetType = typeof WIDGET_TYPES[number];',
  `export type WidgetPayload = ${payloadTypes};`,
  'export type WidgetEnvelopeOf<TPayload = WidgetPayload> = WidgetEnvelope & { payload: TPayload };',
  ''
].join('\n');
await writeFile(outFile, body);
console.log(`Generated ${path.relative(root, outFile)} from ${files.length} schemas`);
